# -*- coding: utf-8 -*-
"""iris flower classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13j_4jx-JR-aevSulYa2wmvSHfwRzq2aL
"""

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import numpy as np

import os
import PIL
import PIL.Image
import tensorflow as tf

print(tf.__version__)

import pandas
import matplotlib.pyplot as plt

iris_dataset = load_iris()

type(iris_dataset)

iris_dataset.data.shape

print(iris_dataset.DESCR)

print("Target names: {}".format(iris_dataset['target_names']))
print("Feature names: {}".format(iris_dataset['feature_names']))
print("Type of data: {}".format(type(iris_dataset['data'])))
print("Shape of data: {}".format(iris_dataset['data'].shape))
print("Type of target: {}".format(type(iris_dataset['target'])))
print("Shape of target: {}".format(iris_dataset['target'].shape))
print("Target:\n{}".format(iris_dataset['target']))

type(iris_dataset.data)

type(iris_dataset.target)

x = iris_dataset.data
y = iris_dataset.target

x

y

#plotting the area of sepal and petal
plt.plot(x[:, 0][y == 0] * x[:, 1][y == 0], x[:, 2][y == 0] * x[:, 3][y == 0], 'r.', label='setosa')
plt.plot(x[:, 0][y == 1] * x[:, 1][y == 1], x[:, 2][y == 1] * x[:, 3][y == 1], 'g.', label='versicolor')
plt.plot(x[:, 0][y == 2] * x[:, 1][y == 2], x[:, 2][y == 2] * x[:, 3][y == 2], 'b.', label='virginica')
plt.legend()
plt.show()

from sklearn.preprocessing import StandardScaler
x = StandardScaler().fit_transform(x)

x_train, x_test, y_train, y_test = train_test_split(x,y)

from sklearn.linear_model import LogisticRegression

log_res = LogisticRegression()

log_res.fit(x_train, y_train)

log_res.score(x_test, y_test)

log_res.score(x, y)
